services:
  modelbridge:
    container_name: modelbridge
    build:
      context: .
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN} # delete after repo is public
        APP_GID: ${APP_GID:-24060} 
        APP_UID: ${APP_UID-24060}
    env_file:
      - .env
    user: "${APP_RUNTIME_GID:-24060}:${APP_RUNTIME_GID:-24060}"
    stdin_open: true
    tty: true
    volumes:
      # Application code sourced from git or superceded by local copy using devcontainer.json
      # Add path to application model folders below
      # Volume maps must match to ensure host symlinks work automatically on the container
      - /data/models:/data/models/:rw
      - /data/LLM/ollama/:/data/LLM/ollama/:rw
      - /data/LLM/kobold/:/data/LLM/kobold/:rw
      - /data/LLM/oobabooga/:/data/LLM/oobabooga/:rw
    environment:
      PYTHONPATH: "/home/app/ai-model-bridge"
      PYTHONDONTWRITEBYTECODE: "1"
    group_add: # delete section if running container as root
      - 6972 # Add the GID for oobabooga-group
networks:
  default:
    name: ai_net
    external: true
