[tool.ruff]
line-length = 99
exclude = ["migrations", "__pycache__"]
extend-ignore = ["F403"]  # Ignore 'import *'
select = ["E", "W", "F"]  # Core linting rules

[tool.ruff.isort]
known-third-party = ["requests", "numpy"]
known-first-party = ["my_project"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
